version: '2'
services:
    eva:
        image: litaio/lita
        command:
            tail -f /dev/null
        ports:
            - "8090:8080"
        volumes:
            - ./runtime/bundle:/var/bundle
            - ./:/app
            - ./share:/share
        depends_on:
            - redis

    redis:
        image: litaio/redis
        ports:
            - "6379:6379"
